### ISSUE TITLE
[BUG] parser.parseStringPromise is not a function

### ISSUE THREAD

**Issue by a-legrand** [node-saml/passport-saml#491] opened 2020-11-03 10:21 UTC
I have "parser.parseStringPromise is not a function" errors on validating incoming samlResponse (was ok in 1.3.5 with same data)

**Environment**
 - Node.js version: 12.18.3
 - passport-saml version: 1.5.0

**Comment by superglue777** [comment] 2020-11-03 11:35
Same here. The issue is wrong `xml2js` dependency version number. In passport-saml I see:
```
"xml2js": "0.4.x",
```
But `parseStringPromise` was added from 0.4.20.
Quick workaround to add this dependency to your project package.json file.

**Comment by janjoost-denbrinker** [comment] 2020-11-03 14:12
Thanks @superglue777 the workaround saved me a lot of time debugging.

**Comment by markstos** [comment] 2020-11-03 14:18
This will be fixed in the next release, maybe today. Subscribe to #489 if you want to be notified.

**Closed by markstos** 2020-11-03 14:18 UTC
Labels: bug
